#!/bin/bash

if [ -L /usr/share/common-lisp/source/memoization ] ; then
 rm -f /usr/share/common-lisp/source/memoization 2> /dev/null > /dev/null || true
fi

if [ -d /usr/share/common-lisp/repositories/memoization ] ; then
 rm -f /usr/share/common-lisp/repositories/memoization/* 2> /dev/null > /dev/null || true
 rmdir /usr/share/common-lisp/repositories/memoization 2> /dev/null > /dev/null || true
fi

#DEBHELPER#

