
        DOUBLE PRECISION FUNCTION CNERR(X)
        DOUBLE PRECISION X

        COMMON /INVCMN/ XC, TOL, NCALL
        DOUBLE PRECISION XC, TOL
        INTEGER NCALL

        DOUBLE PRECISION PNORMS
        EXTERNAL PNORMS
        NCALL = NCALL + 1
        CNERR = XC - PNORMS(X)
        END
