      DOUBLE PRECISION FUNCTION LPN(X)
      COMMON /FUDGE/ NFUDGE
      INTEGER NFUDGE
      DOUBLE PRECISION X
      EXTERNAL PNORMS
      DOUBLE PRECISION PNORMS
      DOUBLE PRECISION T
      DOUBLE PRECISION DLOG
      DOUBLE PRECISION HALF, ZERO
      DATA HALF/0.5D+0/, ZERO/0.D+0/
C
C *** BODY ***
C
      T = PNORMS(X)
      IF (T .GT. ZERO) THEN
         LPN = DLOG(T)
      ELSE
         NFUDGE = NFUDGE + 1
         LPN = -HALF*X**2 - DLOG(-X)
         END IF
 999  RETURN
      END
