      DOUBLE PRECISION FUNCTION PNORMS(X)
      DOUBLE PRECISION X

      EXTERNAL MECDF
      DOUBLE PRECISION D(1), PROB, RHO(1)
      INTEGER IER

      D(1) = X
      CALL MECDF(1, D, RHO, PROB, IER)
      PNORMS = 1.D+0 - PROB
      END
