#!/bin/bash

if [ -L /usr/share/common-lisp/source/cil ] ; then
 rm -f /usr/share/common-lisp/source/cil 2> /dev/null > /dev/null || true
fi

if [ -d /usr/share/common-lisp/repositories/cil ] ; then
 rm -f /usr/share/common-lisp/repositories/cil/* 2> /dev/null > /dev/null || true
 rmdir /usr/share/common-lisp/repositories/cil 2> /dev/null > /dev/null || true
fi

#DEBHELPER#

